# Generated by Django 4.2 on 2025-04-22 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_district_province_remove_location_location_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='district',
            old_name='id',
            new_name='district_id',
        ),
        migrations.RenameField(
            model_name='province',
            old_name='id',
            new_name='province_id',
        ),
        migrations.RenameField(
            model_name='ward',
            old_name='id',
            new_name='ward_id',
        ),
        migrations.AlterField(
            model_name='district',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='core.province'),
        ),
        migrations.AlterField(
            model_name='location',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='core.ward'),
        ),
        migrations.AlterField(
            model_name='ward',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wards', to='core.district'),
        ),
    ]
