# Generated by Django 4.2 on 2025-04-23 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_policy_policy_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LunarCalendar',
        ),
        migrations.RemoveField(
            model_name='znsnotification',
            name='location',
        ),
        migrations.RemoveField(
            model_name='znsnotification',
            name='user',
        ),
        migrations.DeleteModel(
            name='OAFollow',
        ),
        migrations.DeleteModel(
            name='ZNSNotification',
        ),
    ]
