# Generated by Django 4.2 on 2025-05-20 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_user_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='access_token',
            new_name='idByOA',
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
