# Generated by Django 4.2 on 2025-06-09 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_access_token_user_idbyoa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('thumbnail', models.TextField(blank=True, null=True)),
                ('slug', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=24, null=True)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('createdAt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'articles',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.CharField(blank=True, max_length=255, null=True)),
                ('createdAt', models.DateTimeField(blank=True, null=True)),
                ('updatedAt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='MiniAppOption',
            fields=[
                ('id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('showFacebook', models.CharField(max_length=5)),
                ('showYouTube', models.CharField(max_length=5)),
                ('showIntroduction', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'mini_app_options',
            },
        ),
    ]
